name: Deploy to Server

on:
  push:
    branches:
      - main  # V천i 'master', s천ltuvalt sinu haru nimest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: K채ivita uuendus serveris (SSH)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          # K채sud, mis serveris jooksutatakse:
          script: |
            cd /var/www/html
            git pull origin main
            # Vajadusel restardi veebiserver (nt Nginx):
            # sudo systemctl reload nginx
